[package]
name = "sleit/knittutorial"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Input = "sleitnick/input@^2.3.0"
Comm = "sleitnick/comm@^1.0.1"
parallel-worker = "maximumadhd/parallel-worker@^1.0.0"